name: auto-config-js tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: 'test: node ${{ matrix.node }} ${{ matrix.os }} '
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint
      - run: npm test
  publish:
    name: 'Publish Module to NPM'
    needs: test
    # publish only when merged in main on original repo, not on PR
    if: github.repository_owner == 'otaciliolacerda' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: npx semantic-release@latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
