name: auto-config-js tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: 'test: node ${{ matrix.node }} ${{ matrix.os }} '
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 12]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - run: npm i -g yarn
      - run: yarn --immutable
      - run: yarn test
  publish:
    name: 'Publish Module to NPM'
    needs: test
    # publish only when merged in master on original repo, not on PR
    if: github.repository_owner == 'otaciliolacerda' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Publish
        run: npx semantic-release@17
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
